-- HIMWIITA NKOSILATI MUSIC V4
-- Run this entire script in Supabase SQL Editor.

create table if not exists public.albums (
  id text primary key,
  title text not null,
  description text default '',
  cover_url text default '',
  created_at timestamptz default now()
);

create table if not exists public.songs (
  id text primary key,
  title text not null,
  artist text default 'Himwiita Nkosilati',
  album text default 'Tushoma Ndiwe',
  genre text default 'Gospel',
  file_url text not null,
  track integer default 0,
  plays bigint default 0,
  created_at timestamptz default now()
);

create table if not exists public.videos (
  id text primary key,
  title text not null,
  description text default '',
  file_url text not null,
  created_at timestamptz default now()
);

create table if not exists public.lyrics (
  id text primary key,
  song text not null,
  text text default '',
  created_at timestamptz default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  username text not null,
  action text not null,
  item_type text default '',
  item_name text default '',
  created_at timestamptz default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value text not null
);

insert into public.albums (id,title,description)
values ('tushoma-ndiwe','Tushoma Ndiwe','New gospel album by Himwiita Nkosilati.')
on conflict (id) do nothing;

insert into public.site_settings(key,value) values
('artist','Himwiita Nkosilati Music'),
('album','Tushoma Ndiwe'),
('phone','0978038489'),
('manager','Eunice Mwanga'),
('tagline','Worship • Praise • Testimony')
on conflict (key) do nothing;

-- Public read policies. The server uses the service-role key for writes.
alter table public.albums enable row level security;
alter table public.songs enable row level security;
alter table public.videos enable row level security;
alter table public.lyrics enable row level security;
alter table public.site_settings enable row level security;

drop policy if exists "public read albums" on public.albums;
create policy "public read albums" on public.albums for select using (true);
drop policy if exists "public read songs" on public.songs;
create policy "public read songs" on public.songs for select using (true);
drop policy if exists "public read videos" on public.videos;
create policy "public read videos" on public.videos for select using (true);
drop policy if exists "public read lyrics" on public.lyrics;
create policy "public read lyrics" on public.lyrics for select using (true);
drop policy if exists "public read settings" on public.site_settings;
create policy "public read settings" on public.site_settings for select using (true);

-- Storage buckets. Files are public so the website can stream/display them.
insert into storage.buckets (id,name,public) values
('audio','audio',true),('videos','videos',true),('covers','covers',true)
on conflict (id) do update set public=true;

-- Public read access to storage objects.
drop policy if exists "public read audio" on storage.objects;
create policy "public read audio" on storage.objects for select using (bucket_id='audio');
drop policy if exists "public read videos" on storage.objects;
create policy "public read videos" on storage.objects for select using (bucket_id='videos');
drop policy if exists "public read covers" on storage.objects;
create policy "public read covers" on storage.objects for select using (bucket_id='covers');

create or replace function public.increment_song_play(song_id text)
returns void
language sql
security definer
as $$
  update public.songs set plays = coalesce(plays,0) + 1 where id = song_id;
$$;
